# Generated by Django 5.1.4 on 2025-01-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
            ],
        ),
    ]
