# Generated by Django 5.1.4 on 2025-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
